# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# All Rights Reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
image_width: 1824
image_height: 1536
camera_name: OX03F10
camera_matrix:
  rows: 3
  cols: 3
  data: [   1943.33 ,     0.     ,   912    ,
             0.     ,    1943.33 ,   768    ,
             0.     ,     0.     ,    1.    ]
distortion_model: none
distortion_coefficients:
  rows: 1
  cols: 4
  data: [    0.    ,    0.    ,    0.    ,    0.    ]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [   1943.33 ,     0.     ,   912     ,    0.     ,
             0.     ,    1943.33 ,   768     ,    0.     ,
             0.     ,     0.     ,    1.     ,    0.     ]
