set(_AMENT_PACKAGE_NAME "qrb_camera")
set(qrb_camera_VERSION "2.0.1")
set(qrb_camera_MAINTAINER "Zhanye Lin <quic_zhanlin@quicinc.com>")
set(qrb_camera_BUILD_DEPENDS )
set(qrb_camera_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(qrb_camera_BUILD_EXPORT_DEPENDS )
set(qrb_camera_BUILDTOOL_EXPORT_DEPENDS )
set(qrb_camera_EXEC_DEPENDS )
set(qrb_camera_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(qrb_camera_GROUP_DEPENDS )
set(qrb_camera_MEMBER_OF_GROUPS )
set(qrb_camera_DEPRECATED "")
set(qrb_camera_EXPORT_TAGS)
list(APPEND qrb_camera_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
